### ISSUE TITLE
Question about proper commands to use :)

### ISSUE THREAD

**Issue by Destrocamil** [seeraven/gitcache#38]
Hello,

So, I am using gitcache mostly for submodules, since we have more or less 5GB of submodules. 

I followed the setup instructions and I see some stats, however how can I be sure that running `git submodule (...)` is using gitcache?

Normally what I do is `gitcache git submodule (...)` but I am not sure if this is the right way or just using `git clone` will use gitcache behind the hood.

However, on stats, I just see stats of some submodules, not all of them. 

If someone could tell me what is the proper way to use it I would be very grateful!

**Comment by seeraven** [comment]
Hello @Destrocamil ,

first it depends on how you have installed `gitcache`. If you have created the symlink from `git` to `gitcache`, then `gitcache` can intercept all commands. If not, then only explicit calls of `gitcache git` can use the cache. To check whether the symlink wrapper is active, you can check on a Linux machine by calling
```
$ ls -l $(which git)
lrwxrwxrwx 1 root root 8 Dez  7  2022 /repoCache/bin/git -> gitcache
```
Here, you see that `git` is actually overlayed/wrapped by `gitcache`.

Regarding the `git submodule` handling. The only commands that are intercepted are `git submodule init` and `git submodule update`. The `git submodule init` call is intercepted to restore the original "pull" URL before executing the original `git` command. This is necessary to ensure relative submodule URLs are working as expected (relative to the original URL) and are not interpreted relative to the cache directory.
The `git submodule update` call is intercepted to fetch/clone the submodules via `gitcache` to ensure they are also cached, followed by a real `git` call to update everything within the git submodules configuration.

When submodules are added using `git submodule add ...` there is no gitcache active. I'm not 100% sure how that can be handled using gitcache, because the entries in `.gitmodules` should point to the original URLs whereas the checkout should point to the cache. So in this case, whenever you add a new submodule, the cache won't be used. However, when you clone again the parent repository and perform a `git submodule update --init` call, all submodules should be cached and configured accordingly.

Git submodules are somewhat tricky, so there might be some other parts missing in the caching strategy. If you have a toy-example to pinpoint the missing feature, I'm happy to try and add it to `gitcache`.

**Comment by Destrocamil** [comment]
Hello @seeraven , 
Thanks a lot for your detailed answer, really helpful. 
I was having an issue that I was not able to see stats of repos being cached and I found it very odd. Only when running with `gitcache git` I was able to see something.. Turned out that the symlink was not present, despite being almost sure I did that step. 
Now I can see some stats, but seems not all the submodules are cached ? Tried locally and then later via CI, the time is way way less time, so clearly it is using gitcache for the ones already cached and I can see some stats now, but I find it odd with some are not cached, even though they belong to the same `.gitmodules`. Anyway, this project is amazing and I think it can help a lot, have to do few more tests.

Thanks A LOT for your hard work ❤️
