### ISSUE TITLE
Add shallow clone

### ISSUE THREAD

**Issue by Darejkal** [seeraven/gitcache#53]
It seems that when using git clone with specified depth (eg: --depth 1), gitcache will still try to mirror the entire repo.

**Comment by Youw** [comment]
I believe that's pretty much the whole point of gitcache - to have a mirror of the entire repo, which is a potentially heavy operation, but only during the initial clone, so that at any point of time in the future, the checkout/clone/etc. of the repo would be as fast as local copy of the data, and the full history is still available (often needed, e.g. to build a changelog, etc.).
