### ISSUE TITLE
Unable to run on MacOS

### ISSUE THREAD

**Issue by waipeng** [seeraven/gitcache#58]
After getting through the MacOS security messages, I get the following

```
“Python.framework” is damaged and can’t be opened. You should move it to the Bin.
```

Sonoma 14.7.1 (23H222) on Apple M1

This is the trace

```[12748] Failed to load Python shared library '/Users/jake/Applications/gitcache_v1.0.18_Darwin_arm64/_internal/Python': dlopen: dlopen(/Users/jake/Applications/gitcache_v1.0.18_Darwin_arm64/_internal/Python, 0x000A): tried: '/Users/jake/Applications/gitcache_v1.0.18_Darwin_arm64/_internal/Python' (code signature in <BB235480-7EF7-3727-8512-14B6E41B25B4> '/Users/jake/Applications/gitcache_v1.0.18_Darwin_arm64/_internal/Python.framework/Versions/3.12/Python' not valid for use in process: library load disallowed by system policy), '/System/Volumes/Preboot/Cryptexes/OS/Users/jake/Applications/gitcache_v1.0.18_Darwin_arm64/_internal/Python' (no such file), '/Users/jake/Applications/gitcache_v1.0.18_Darwin_arm64/_internal/Python' (code signature in <BB235480-7EF7-3727-8512-14B6E41B25B4> '/Users/jake/Applications/gitcache_v1.0.18_Darwin_arm64/_internal/Python.framework/Versions/3.12/Python' not valid for use in process: library load disallowed by system policy), '/Users/jake/Applications/gitcache_v1.0.18_Darwin_arm64/_internal/Python.framework/Versions/3.12/Python' (code signature in <BB235480-7EF7-3727-8512-14B6E41B25B4> '/Users/jake/Applications/gitcache_v1.0.18_Darwin_arm64/_internal/Python.framework/Versions/3.12/Python' not valid for use in process: library load disallowed by system policy), '/System/Volumes/Preboot/Cryptexes/OS/Users/jake/Applications/gitcache_v1.0.18_Darwin_arm64/_internal/Python.framework/Versions/3.12/Python' (no such file), '/Users/jake/Applications/gitcache_v1.0.18_Darwin_arm64/_internal/Python.framework/Versions/3.12/Python' (code signature in <BB235480-7EF7-3727-8512-14B6E41B25B4> '/Users/jake/Applications/gitcache_v1.0.18_Darwin_arm64/_internal/Python.framework/Versions/3.12/Python' not valid for use in process: library load disallowed by system policy), '/Library/Frameworks/Python.framework/Versions/3.12/Python' (no such file), '/System/Library/Frameworks/Python.framework/Versions/3.12/Python' (no such file, not in dyld cache)```

I couldn't figure out how to proceed. Do you think this is a MacOS issue or PyInstaller issue? Is there a way to run it without using the prepackaged Python?

Any advice is appreciated. Thanks! 😄

**Comment by seeraven** [comment]
Unfortunately I have no experience with MacOS and had added the binaries for some other folks working on MacOS.
But yes, you can of course run gitcache from source. In summary, you have to
- Install all pip requirements. The requirements are located in `pip_deps` and can be installed with `pip install -r pip_deps/<file>`. Here you have to pick the right one matching your python version. I would guess something like `pip_deps/requirements-darwin-py3.12.4.txt`.
- Test if you can execute `src/gitcache` now by calling it like `src/gitcache --help`. You should see no error about missing modules.
- Now you can follow the usual installation steps, but instead of using the pyInstaller binary use the script. Just remember that the script should not be moved alone, otherwise it won't be able to find its modules.

**Comment by Youw** [comment]
Interesting...
Try to run:
```sh
xattr -cr /Users/jake/Applications/gitcache_v1.0.18_Darwin_arm64
```
This is to clear the quarantine attribute for the file downloaded from web.

**Comment by waipeng** [comment]
OH WOW Thanks that works!

**Comment by seeraven** [comment]
Good to hear! And thanks @Youw for the solution! I've added it to the README to help others falling into that trap.

**Comment by Youw** [comment]
That is more a workaround, not a solution. The "right" way is to properly sign/notarize the package.
